version: 2
updates:

  # Manage Github Actions versions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      # Check for updates at 7am UTC.
      time: "07:00"
    commit-message:
      prefix: "ci:"
    labels:
      - c:deps
      - c:testing

  # Manage Javascript package versions.
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      # Check for updates at 7am UTC.
      time: "07:00"
    labels:
      - c:deps
